# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='actions.proto',
  package='org.seekloud.esheepapi.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ractions.proto\x12\x19org.seekloud.esheepapi.pb\")\n\x05Swing\x12\x0e\n\x06radian\x18\x01 \x01(\x02\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02*Y\n\x04Move\x12\x06\n\x02up\x10\x00\x12\x08\n\x04\x64own\x10\x01\x12\x08\n\x04left\x10\x02\x12\t\n\x05right\x10\x03\x12\x08\n\x04l_up\x10\x04\x12\x08\n\x04r_up\x10\x05\x12\n\n\x06l_down\x10\x06\x12\n\n\x06r_down\x10\x07\x62\x06proto3')
)

_MOVE = _descriptor.EnumDescriptor(
  name='Move',
  full_name='org.seekloud.esheepapi.pb.Move',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='up', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='down', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='left', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='right', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='l_up', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='r_up', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='l_down', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='r_down', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=87,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_MOVE)

Move = enum_type_wrapper.EnumTypeWrapper(_MOVE)
up = 0
down = 1
left = 2
right = 3
l_up = 4
r_up = 5
l_down = 6
r_down = 7



_SWING = _descriptor.Descriptor(
  name='Swing',
  full_name='org.seekloud.esheepapi.pb.Swing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radian', full_name='org.seekloud.esheepapi.pb.Swing.radian', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='org.seekloud.esheepapi.pb.Swing.distance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['Swing'] = _SWING
DESCRIPTOR.enum_types_by_name['Move'] = _MOVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Swing = _reflection.GeneratedProtocolMessageType('Swing', (_message.Message,), dict(
  DESCRIPTOR = _SWING,
  __module__ = 'actions_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.esheepapi.pb.Swing)
  ))
_sym_db.RegisterMessage(Swing)


# @@protoc_insertion_point(module_scope)
