# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='observations.proto',
  package='org.seekloud.esheepapi.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12observations.proto\x12\x19org.seekloud.esheepapi.pb\"\xdf\x02\n\x12LayeredObservation\x12;\n\x0flocation_in_map\x18\x01 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x36\n\nbackground\x18\x02 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x32\n\x06things\x18\x03 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x33\n\x07players\x18\x04 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x37\n\x0bself_player\x18\x05 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x32\n\x06states\x18\x06 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\"L\n\x07ImgData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x14\n\x0cpixel_length\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x62\x06proto3')
)




_LAYEREDOBSERVATION = _descriptor.Descriptor(
  name='LayeredObservation',
  full_name='org.seekloud.esheepapi.pb.LayeredObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location_in_map', full_name='org.seekloud.esheepapi.pb.LayeredObservation.location_in_map', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='background', full_name='org.seekloud.esheepapi.pb.LayeredObservation.background', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='things', full_name='org.seekloud.esheepapi.pb.LayeredObservation.things', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='org.seekloud.esheepapi.pb.LayeredObservation.players', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='self_player', full_name='org.seekloud.esheepapi.pb.LayeredObservation.self_player', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='states', full_name='org.seekloud.esheepapi.pb.LayeredObservation.states', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=401,
)


_IMGDATA = _descriptor.Descriptor(
  name='ImgData',
  full_name='org.seekloud.esheepapi.pb.ImgData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='org.seekloud.esheepapi.pb.ImgData.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='org.seekloud.esheepapi.pb.ImgData.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_length', full_name='org.seekloud.esheepapi.pb.ImgData.pixel_length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='org.seekloud.esheepapi.pb.ImgData.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=479,
)

_LAYEREDOBSERVATION.fields_by_name['location_in_map'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['background'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['things'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['players'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['self_player'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['states'].message_type = _IMGDATA
DESCRIPTOR.message_types_by_name['LayeredObservation'] = _LAYEREDOBSERVATION
DESCRIPTOR.message_types_by_name['ImgData'] = _IMGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayeredObservation = _reflection.GeneratedProtocolMessageType('LayeredObservation', (_message.Message,), dict(
  DESCRIPTOR = _LAYEREDOBSERVATION,
  __module__ = 'observations_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.esheepapi.pb.LayeredObservation)
  ))
_sym_db.RegisterMessage(LayeredObservation)

ImgData = _reflection.GeneratedProtocolMessageType('ImgData', (_message.Message,), dict(
  DESCRIPTOR = _IMGDATA,
  __module__ = 'observations_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.esheepapi.pb.ImgData)
  ))
_sym_db.RegisterMessage(ImgData)


# @@protoc_insertion_point(module_scope)
