# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='observations.proto',
  package='org.seekloud.esheepapi.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12observations.proto\x12\x19org.seekloud.esheepapi.pb\"\xdd\x03\n\x12LayeredObservation\x12\x34\n\x08location\x18\x01 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12=\n\x11immutable_element\x18\x02 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12;\n\x0fmutable_element\x18\x03 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x32\n\x06\x62odies\x18\x04 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12;\n\x0f\x61sset_ownership\x18\x05 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x36\n\nself_asset\x18\x06 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x37\n\x0bself_status\x18\x07 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\x12\x33\n\x07pointer\x18\x08 \x01(\x0b\x32\".org.seekloud.esheepapi.pb.ImgData\"L\n\x07ImgData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x14\n\x0cpixel_length\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x62\x06proto3')
)




_LAYEREDOBSERVATION = _descriptor.Descriptor(
  name='LayeredObservation',
  full_name='org.seekloud.esheepapi.pb.LayeredObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='org.seekloud.esheepapi.pb.LayeredObservation.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='immutable_element', full_name='org.seekloud.esheepapi.pb.LayeredObservation.immutable_element', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mutable_element', full_name='org.seekloud.esheepapi.pb.LayeredObservation.mutable_element', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bodies', full_name='org.seekloud.esheepapi.pb.LayeredObservation.bodies', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_ownership', full_name='org.seekloud.esheepapi.pb.LayeredObservation.asset_ownership', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='self_asset', full_name='org.seekloud.esheepapi.pb.LayeredObservation.self_asset', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='self_status', full_name='org.seekloud.esheepapi.pb.LayeredObservation.self_status', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pointer', full_name='org.seekloud.esheepapi.pb.LayeredObservation.pointer', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=527,
)


_IMGDATA = _descriptor.Descriptor(
  name='ImgData',
  full_name='org.seekloud.esheepapi.pb.ImgData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='org.seekloud.esheepapi.pb.ImgData.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='org.seekloud.esheepapi.pb.ImgData.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_length', full_name='org.seekloud.esheepapi.pb.ImgData.pixel_length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='org.seekloud.esheepapi.pb.ImgData.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=605,
)

_LAYEREDOBSERVATION.fields_by_name['location'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['immutable_element'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['mutable_element'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['bodies'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['asset_ownership'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['self_asset'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['self_status'].message_type = _IMGDATA
_LAYEREDOBSERVATION.fields_by_name['pointer'].message_type = _IMGDATA
DESCRIPTOR.message_types_by_name['LayeredObservation'] = _LAYEREDOBSERVATION
DESCRIPTOR.message_types_by_name['ImgData'] = _IMGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayeredObservation = _reflection.GeneratedProtocolMessageType('LayeredObservation', (_message.Message,), dict(
  DESCRIPTOR = _LAYEREDOBSERVATION,
  __module__ = 'observations_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.esheepapi.pb.LayeredObservation)
  ))
_sym_db.RegisterMessage(LayeredObservation)

ImgData = _reflection.GeneratedProtocolMessageType('ImgData', (_message.Message,), dict(
  DESCRIPTOR = _IMGDATA,
  __module__ = 'observations_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.esheepapi.pb.ImgData)
  ))
_sym_db.RegisterMessage(ImgData)


# @@protoc_insertion_point(module_scope)
