# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import api_pb2 as api__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='org.seekloud.esheepapi.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x12\x19org.seekloud.esheepapi.pb\x1a\tapi.proto2\x87\x08\n\x0b\x45sheepAgent\x12`\n\ncreateRoom\x12(.org.seekloud.esheepapi.pb.CreateRoomReq\x1a(.org.seekloud.esheepapi.pb.CreateRoomRsp\x12X\n\x08joinRoom\x12&.org.seekloud.esheepapi.pb.JoinRoomReq\x1a$.org.seekloud.esheepapi.pb.SimpleRsp\x12T\n\tleaveRoom\x12!.org.seekloud.esheepapi.pb.Credit\x1a$.org.seekloud.esheepapi.pb.SimpleRsp\x12[\n\x0b\x61\x63tionSpace\x12!.org.seekloud.esheepapi.pb.Credit\x1a).org.seekloud.esheepapi.pb.ActionSpaceRsp\x12Y\n\nsystemInfo\x12!.org.seekloud.esheepapi.pb.Credit\x1a(.org.seekloud.esheepapi.pb.SystemInfoRsp\x12T\n\x06\x61\x63tion\x12$.org.seekloud.esheepapi.pb.ActionReq\x1a$.org.seekloud.esheepapi.pb.ActionRsp\x12[\n\x0bobservation\x12!.org.seekloud.esheepapi.pb.Credit\x1a).org.seekloud.esheepapi.pb.ObservationRsp\x12m\n\x13observationWithInfo\x12!.org.seekloud.esheepapi.pb.Credit\x1a\x31.org.seekloud.esheepapi.pb.ObservationWithInfoRsp0\x01\x12Q\n\x06inform\x12!.org.seekloud.esheepapi.pb.Credit\x1a$.org.seekloud.esheepapi.pb.InformRsp\x12X\n\rreincarnation\x12!.org.seekloud.esheepapi.pb.Credit\x1a$.org.seekloud.esheepapi.pb.SimpleRsp\x12_\n\x0c\x63urrentFrame\x12!.org.seekloud.esheepapi.pb.Credit\x1a*.org.seekloud.esheepapi.pb.CurrentFrameRsp0\x01\x62\x06proto3')
  ,
  dependencies=[api__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ESHEEPAGENT = _descriptor.ServiceDescriptor(
  name='EsheepAgent',
  full_name='org.seekloud.esheepapi.pb.EsheepAgent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=56,
  serialized_end=1087,
  methods=[
  _descriptor.MethodDescriptor(
    name='createRoom',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.createRoom',
    index=0,
    containing_service=None,
    input_type=api__pb2._CREATEROOMREQ,
    output_type=api__pb2._CREATEROOMRSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='joinRoom',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.joinRoom',
    index=1,
    containing_service=None,
    input_type=api__pb2._JOINROOMREQ,
    output_type=api__pb2._SIMPLERSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='leaveRoom',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.leaveRoom',
    index=2,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._SIMPLERSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='actionSpace',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.actionSpace',
    index=3,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._ACTIONSPACERSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='systemInfo',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.systemInfo',
    index=4,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._SYSTEMINFORSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='action',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.action',
    index=5,
    containing_service=None,
    input_type=api__pb2._ACTIONREQ,
    output_type=api__pb2._ACTIONRSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='observation',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.observation',
    index=6,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._OBSERVATIONRSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='observationWithInfo',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.observationWithInfo',
    index=7,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._OBSERVATIONWITHINFORSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='inform',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.inform',
    index=8,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._INFORMRSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reincarnation',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.reincarnation',
    index=9,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._SIMPLERSP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='currentFrame',
    full_name='org.seekloud.esheepapi.pb.EsheepAgent.currentFrame',
    index=10,
    containing_service=None,
    input_type=api__pb2._CREDIT,
    output_type=api__pb2._CURRENTFRAMERSP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESHEEPAGENT)

DESCRIPTOR.services_by_name['EsheepAgent'] = _ESHEEPAGENT

# @@protoc_insertion_point(module_scope)
